---
ID: "0165c7de-50b6-45b6-9241-036ce372f105"
Parent: "7a8d0b68-6a39-4ae7-8ccf-bcb54392c235"
Template: "7a8d0b68-6a39-4ae7-8ccf-bcb54392c235"
Path: /sitecore/templates/Project/tac/Events/Contents/Hero Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{450EE89A-2141-443C-A610-43DD4AA7A3A3}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "ffe78fae-8b41-4e06-9989-f01a3dedb295"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250917T064600Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\kcunanan@deloitte.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\kcunanan@deloitte.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e531fe0c-c15c-4940-8974-50c21aa1db48"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\kcunanan@deloitte.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250917T064622Z
